package com.cpabe.abe_lib.bsw;
import it.unisa.dia.gas.jpbc.Element;

public class Ircpabe {
    //new added key structure
    public Element g1;
    public Element g1b;
    public Element g1bb;
    public Element g2;
    public Element g2b;
    public Element e_gg_alpha;
    public Element h1;
    public Element h2;
    public Element h3;
    public Element h4;
    public Element h5;
    public Element h6;
    public Element h7;
    public Element h8;
    public Element h9;
    public Element h10;
    public Element gsIDs_org1;
    public Element gsIDs_org2;
    public Element gsIDs_org3;
    public Element gsIDs_org4;
    public Element gsIDs_org5;
    public Element gsIDs_org6;
    public Element gbsIDs_org1;
    public Element gbsIDs_org2;
    public Element gbsIDs_org3;
    public Element gbsIDs_org4;
    public Element gbsIDs_org5;
    public Element gbsIDs_org6;
    public Element sID_org1;
    public Element sID_org2;
    public Element sID_org3;
    public Element sID_org4;
    public Element sID_org5;
    public Element sID_org6;
    public Element sIDr_org1;
    public Element sIDr_org2;
    public Element sIDr_org3;
    public Element sIDr_org4;
    public Element sIDr_org5;
    public Element sIDr_org6;
    public Element hb1;
    public Element hb2;
    public Element hb3;
    public Element hb4;
    public Element hb5;
    public Element hb6;
    public Element hb7;
    public Element hb8;
    public Element hb9;
    public Element hb10;
    public Element hbb1;
    public Element hbb2;
    public Element hbb3;
    public Element hbb4;
    public Element hbb5;
    public Element hbb6;
    public Element hbb7;
    public Element hbb8;
    public Element hbb9;
    public Element hbb10;
}
